### ISSUE TITLE
MicroPython 1.8 on Huzzah ESP8266 with 128x32 OLED

### ISSUE THREAD

**Issue by ghost** [adafruit/Adafruit_Python_SSD1306#11]
Hi Mike, I am an an early adopter of MicroPython on the ESP8266 and would very much like to get the 128x32 OLED feather wing working there. I noticed that the feather libraries pull in SSD1306.h and in researching found this library for BB and Pi. Any pointers before I start hacking to try and make this work? :hammer:

**Comment by ladyada** [comment]
hiya this library is being deprecated, there are MicroPython OLED libraries you can use besides this one. thanx!
