### ISSUE TITLE
multiple oled display to single raspberry pi

### ISSUE THREAD

**Issue by rishikeshayre1310** [adafruit/Adafruit_Python_SSD1306#20]
Hello
is it possible to interface multiple oled display through i2c. and if so what changes need to be done.

**Comment by MarkFiechtner** [comment]
I don't see a way to set the I2C address on the SSD1306 so you might need a unique I2C bus per device.  You didn't say what type of processor board you are using so it would depend on your hardware.
The 1306 data sheet is here if you want to look into it:
https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf
Good luck.

**Comment by ladyada** [comment]
hiya, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring
