### ISSUE TITLE
dim() should call set_contrast()

### ISSUE THREAD

**Issue by eprst** [adafruit/Adafruit_Python_SSD1306#23]
`dim()` on line [235](https://github.com/adafruit/Adafruit_Python_SSD1306/blob/master/Adafruit_SSD1306/SSD1306.py#L235) misses a call to `self.set_contrast(contrast)`.

Sorry, too lazy to create a PR for this.

**Comment by ladyada** [comment]
hiya, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring

the new library does not have a 'dim' function

https://github.com/adafruit/Adafruit_CircuitPython_SSD1306/blob/master/adafruit_ssd1306.py#L123
