### ISSUE TITLE
happy cat path is wrong

### ISSUE THREAD

**Issue by NeilHendrick** [adafruit/Adafruit_Python_SSD1306#29]
There is a small error in the example scripts when trying to display images. The images are referred to without a path, and the result is that the script will crash when trying to display the referenced image. 

For example, 
`IOError: [Errno 2] No such file or directory: 'happycat_oled_32.ppm'`

To fix this, I simply edited the buttons.py script at line 154 with an absolute path to the image file.
It was 👍 
`catImage = Image.open('happycat_oled_64.ppm').convert('1')`

Changed to:
`catImage = Image.open('/home/pi/Adafruit_Python_SSD1306/examples/happycat_oled_64.ppm').convert('1')`

now, it works fine.

**Comment by ladyada** [comment]
it depends on the directory you're running from - you should have it in the same directory you're running the script!
