### ISSUE TITLE
PIL or Pillow is not listed in `setup.py` to run

### ISSUE THREAD

**Issue by walchko** [adafruit/Adafruit_Python_SSD1306#36]
Why isn't PIL or Pillow listed in the `install_requires` field in `setup.py`? As far as I can tell, you need it to run this so it should be listed for completeness.

**Comment by ladyada** [comment]
hiya, this library is being deprecated - we have a similar library that works with Python3 and modern linux computers. please check out this guide for more info
https://learn.adafruit.com/monochrome-oled-breakouts/python-wiring
