### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by jwatte** [adafruit/Adafruit_Python_SSD1306#6]
The documentation page doesn't completely document the steps necessary to make I2C work.
Specifically, on a virgin Raspberry Pi, you need to do the following:
Put a # comment in front of the blacklist i2c-bcm2708 line in /etc/modprobe.d/raspi-blacklist.conf
Add the modules i2c-bcm2708 AND i2c-dev to the file /etc/modules <-- this took me a while to find out!
Restart, or run modprobe to install the modules.
After this, you can find the i2c bus using i2cscan -l. Before that, you will get "No such file or device" or similar errors.

**Comment by tdicola** [comment]
Oh thanks for the feedback and digging in to find the solution.  It looks like this guide page should call out enabling I2C on the Pi like some later tutorials mention.  Just updated the page here to call it out: https://learn.adafruit.com/ssd1306-oled-displays-with-raspberry-pi-and-beaglebone-black/wiring  Thanks for raising the issue!
