### ISSUE TITLE
Changing font / size

### ISSUE THREAD

**Issue by Toshibass** [adafruit/Adafruit_Python_SSD1306#7]
I have succeeded to installing and run the examples included in this code on a ssd1306 i2c device, but I primarily want to display text, again I have succeeded but I cannot understand how to change the font size, it occurred to me that maybe I need to use a larger font type, so I followed the advice and downloaded Minecraftia.ttf', 8 from http://www.dafont.com/bitmap.php but when I try to use it I get the following error : 
    font = ImageFont.truetype('Minecraftia.ttf', 8)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 218, in truetype
    return FreeTypeFont(filename, size, index, encoding)
  File "/usr/lib/python2.7/dist-packages/PIL/ImageFont.py", line 134, in __init__
    self.font = core.getfont(file, size, index, encoding)
IOError: cannot open resource

So the question is how do I change the size of text and how do I actually utilize a different font type ?

Thanks and regards

**Comment by tdicola** [comment]
Make sure to copy the Minecraftia.ttf file into the same directory as your python script.  From the error it looks like it most likely can't find the file.  If it's a .zip file be sure to uncompress it first too (you can run `sudo apt-get install unzip` and then run the `unzip` command with the name of a zip file to uncompress).  Also be sure the ImageFont.truetype command parameter has exactly the same filename as the .ttf file--capitalization, etc. is important to match. 

Once you've got the .ttf font loading then to change the font size just increase the size of second parameter to the ImageFont.truetype function.  So for example the line you have uses the size 8, but if you want to bump up to 16 you would use `font = ImageFont.truetype('Minecraftia.ttf', 16)`.
